import { User, WasteListing, Bid, Claim, Pickup, NotificationItem, MessageItem } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-producer-1',
    email: 'techcorp@wastexchange.com',
    name: 'Apex Infotech Solutions',
    role: 'WASTE_PRODUCER',
    organization: 'Apex Infotech Pvt Ltd',
    phone: '+91 98765 43210',
    address: 'Plot 42, Tech Park, Gachibowli',
    city: 'Hyderabad',
    area: 'Financial District',
    verificationStatus: 'VERIFIED',
    verificationBadge: 'Verified IT Producer',
    rating: 4.9,
    completedExchangesCount: 48,
    avatarUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-producer-2',
    email: 'grandhotel@wastexchange.com',
    name: 'Grand Horizon Hotel & Banquet',
    role: 'WASTE_PRODUCER',
    organization: 'Grand Horizon Hospitality',
    phone: '+91 98123 77890',
    address: '88 Circular Road, Jubilee Hills',
    city: 'Hyderabad',
    area: 'Jubilee Hills',
    verificationStatus: 'VERIFIED',
    verificationBadge: 'Verified Food Producer',
    rating: 4.7,
    completedExchangesCount: 112,
    avatarUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-recycler-1',
    email: 'greencycle@wastexchange.com',
    name: 'GreenCycle E-Waste Recyclers',
    role: 'RECYCLER_INDUSTRY',
    organization: 'GreenCycle Environmental Ltd',
    phone: '+91 97111 22334',
    address: 'Industrial Development Zone, Zone B',
    city: 'Hyderabad',
    area: 'Cherlapally',
    verificationStatus: 'VERIFIED',
    verificationBadge: 'Verified E-Recycler',
    rating: 4.8,
    completedExchangesCount: 156,
    avatarUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-farmer-1',
    email: 'krishi.farms@wastexchange.com',
    name: 'Rameshwar Organic Farming Co-op',
    role: 'FARMER_ORGANIC_USER',
    organization: 'Krishi Vikas Farmers Association',
    phone: '+91 94400 55667',
    address: 'Green Belt Outskirts, Sector 12',
    city: 'Hyderabad',
    area: 'Shamirpet',
    verificationStatus: 'VERIFIED',
    verificationBadge: 'Verified Agricultural User',
    rating: 4.9,
    completedExchangesCount: 89,
    avatarUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb231fc?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-admin-1',
    email: 'admin@wastexchange.com',
    name: 'Smart Exchange Admin Team',
    role: 'ADMIN',
    organization: 'Smart Waste Exchange Platform',
    phone: '+91 80000 11223',
    address: 'HQ Innovation Hub, Tower 3',
    city: 'Hyderabad',
    area: 'HITEC City',
    verificationStatus: 'VERIFIED',
    verificationBadge: 'Platform Admin',
    rating: 5.0,
    completedExchangesCount: 999,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_LISTINGS: WasteListing[] = [
  // E-WASTE LISTINGS
  {
    id: 'lst-ewaste-101',
    producerId: 'usr-producer-1',
    producerName: 'Apex Infotech Solutions',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified IT Producer',
    type: 'E_WASTE',
    categoryName: 'Computer Servers & Motherboards',
    title: '35 Dismantled Server Motherboards & High-Grade Circuit Boards',
    description: 'Decommissioned server motherboards from corporate data center upgrade. Fully intact PCB traces, gold-plated connectors, capacitors, and ICs suitable for precious metal recovery and urban mining.',
    quantity: 65,
    unit: 'kg',
    condition: 'Decommissioned / Scrap',
    source: 'Corporate IT Infrastructure',
    availabilityDate: '2026-09-06',
    address: 'Plot 42, Tech Park, Gachibowli',
    city: 'Hyderabad',
    area: 'Financial District',
    distanceKm: 3.2,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Pickup Required',
    expectedPrice: 18500,
    isFree: false,
    status: 'AVAILABLE',
    createdAt: '2026-09-04T10:30:00Z',
  },
  {
    id: 'lst-ewaste-102',
    producerId: 'usr-producer-1',
    producerName: 'Apex Infotech Solutions',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified IT Producer',
    type: 'E_WASTE',
    categoryName: 'Laptops & Monitors',
    title: 'Batch of 18 Dual-Core Laptops & LED Display Panels',
    description: 'Non-working office laptops with intact screens, copper heatsinks, battery modules (lithium-ion), and RAM sticks. Ideal for electronic component harvesting and certified recycling.',
    quantity: 45,
    unit: 'kg',
    condition: 'Non-Working / Parts Only',
    source: 'IT Office Hardware',
    availabilityDate: '2026-09-07',
    address: 'Plot 42, Tech Park, Gachibowli',
    city: 'Hyderabad',
    area: 'Financial District',
    distanceKm: 3.2,
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Both',
    expectedPrice: 12000,
    isFree: false,
    status: 'BIDDING',
    createdAt: '2026-09-03T14:15:00Z',
  },
  {
    id: 'lst-ewaste-103',
    producerId: 'usr-producer-1',
    producerName: 'Apex Infotech Solutions',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified IT Producer',
    type: 'E_WASTE',
    categoryName: 'Cables & Power Supplies',
    title: '120 kg Assorted Copper Cables, SMPS Power Units & Adapters',
    description: 'High-purity insulated copper wiring, power supplies, Ethernet cables, and heavy transformers from office relocation project.',
    quantity: 120,
    unit: 'kg',
    condition: 'Mixed Cables & Scrap',
    source: 'Network Relocation',
    availabilityDate: '2026-09-05',
    address: 'Plot 42, Tech Park, Gachibowli',
    city: 'Hyderabad',
    area: 'Financial District',
    distanceKm: 3.2,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Pickup Required',
    expectedPrice: 9500,
    isFree: false,
    status: 'AVAILABLE',
    createdAt: '2026-09-05T08:00:00Z',
  },

  // ORGANIC WASTE LISTINGS
  {
    id: 'lst-organic-201',
    producerId: 'usr-producer-2',
    producerName: 'Grand Horizon Hotel & Banquet',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified Food Producer',
    type: 'ORGANIC_WASTE',
    categoryName: 'Vegetable Trimmings & Kitchen Organic Scrap',
    title: '450 kg Fresh Vegetable Peelings & Uncooked Market Trimmings',
    description: 'Source-segregated raw vegetable scraps (cabbage leaves, carrot peels, potato skins, onion skins) collected daily from banquet kitchen prep operations. Completely free from plastic, foil, or chemical detergents.',
    quantity: 450,
    unit: 'kg',
    condition: 'Fresh Segregated Organic Waste',
    source: 'Commercial Kitchen Prep',
    availabilityDate: '2026-09-05',
    expiryDate: '2026-09-07',
    address: '88 Circular Road, Jubilee Hills',
    city: 'Hyderabad',
    area: 'Jubilee Hills',
    distanceKm: 4.8,
    images: [
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Self Drop-off',
    isFree: true,
    contaminationStatus: 'None',
    suitableUse: 'Composting',
    safetyDisclaimerAccepted: true,
    status: 'AVAILABLE',
    createdAt: '2026-09-05T06:00:00Z',
  },
  {
    id: 'lst-organic-202',
    producerId: 'usr-producer-2',
    producerName: 'Rythu Vegetable Wholesale Market',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified Market Vendor',
    type: 'ORGANIC_WASTE',
    categoryName: 'Agricultural Produce Leftovers',
    title: '1.2 Tons Unsold Tomato & Leafy Greens Bulk Waste',
    description: 'Overripe tomatoes, outer lettuce leaves, and spinach stalks gathered at market close. High nitrogen content ideal for rapid aerobic composting or anaerobic biogas generation systems.',
    quantity: 1200,
    unit: 'kg',
    condition: 'Soft / Overripe Produce',
    source: 'Wholesale Farmers Market',
    availabilityDate: '2026-09-05',
    expiryDate: '2026-09-06',
    address: 'Rythu Bazaar Complex, Moosapet',
    city: 'Hyderabad',
    area: 'Moosapet',
    distanceKm: 6.1,
    images: [
      'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Pickup Required',
    isFree: true,
    contaminationStatus: 'Minor Organic Mix',
    suitableUse: 'Biogas',
    safetyDisclaimerAccepted: true,
    status: 'AVAILABLE',
    createdAt: '2026-09-05T07:30:00Z',
  },
  {
    id: 'lst-organic-203',
    producerId: 'usr-producer-2',
    producerName: 'Grand Horizon Hotel & Banquet',
    producerRole: 'WASTE_PRODUCER',
    producerVerification: 'VERIFIED',
    producerBadge: 'Verified Food Producer',
    type: 'ORGANIC_WASTE',
    categoryName: 'Spent Coffee Grounds & Fruit Pulp',
    title: '180 kg Spent Espresso Coffee Grounds & Citrus Peel',
    description: 'Clean coffee grounds from hotel espresso bars packed in clean breathable bags. Excellent nitrogen-to-carbon soil conditioner for horticulture, mushroom cultivation, and vermicomposting.',
    quantity: 180,
    unit: 'kg',
    condition: 'Clean Moisture-Rich Scrap',
    source: 'Hotel Beverage Outlets',
    availabilityDate: '2026-09-05',
    expiryDate: '2026-09-10',
    address: '88 Circular Road, Jubilee Hills',
    city: 'Hyderabad',
    area: 'Jubilee Hills',
    distanceKm: 4.8,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80'
    ],
    preferredCollection: 'Both',
    isFree: true,
    contaminationStatus: 'None',
    suitableUse: 'Agricultural Soil Conditioning',
    safetyDisclaimerAccepted: true,
    status: 'CLAIMED',
    createdAt: '2026-09-04T12:00:00Z',
  }
];

export const INITIAL_BIDS: Bid[] = [
  {
    id: 'bid-001',
    listingId: 'lst-ewaste-101',
    bidderId: 'usr-recycler-1',
    bidderName: 'GreenCycle E-Waste Recyclers',
    bidderBadge: 'Verified E-Recycler',
    amount: 19500,
    notes: 'We can collect tomorrow morning between 9 AM - 11 AM using our certified hazmat transport vehicle.',
    status: 'PENDING',
    createdAt: '2026-09-04T16:20:00Z',
  },
  {
    id: 'bid-002',
    listingId: 'lst-ewaste-102',
    bidderId: 'usr-recycler-1',
    bidderName: 'GreenCycle E-Waste Recyclers',
    bidderBadge: 'Verified E-Recycler',
    amount: 12500,
    notes: 'Full payment upon physical audit at pickup. All e-waste destruction certificates provided.',
    status: 'ACCEPTED',
    createdAt: '2026-09-04T11:10:00Z',
  }
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'clm-001',
    listingId: 'lst-organic-201',
    claimerId: 'usr-farmer-1',
    claimerName: 'Rameshwar Organic Farming Co-op',
    claimerBadge: 'Verified Agricultural User',
    intendedUse: 'Composting for 15-acre organic vegetable farm and soil enrichment.',
    notes: 'We will bring our tractor trailer for quick loading at your back loading dock.',
    status: 'PENDING',
    createdAt: '2026-09-05T08:15:00Z',
  },
  {
    id: 'clm-002',
    listingId: 'lst-organic-203',
    claimerId: 'usr-farmer-1',
    claimerName: 'Rameshwar Organic Farming Co-op',
    claimerBadge: 'Verified Agricultural User',
    intendedUse: 'Vermicomposting substrate for bio-fertilizer manufacturing unit.',
    notes: 'Claimed and approved.',
    status: 'APPROVED',
    createdAt: '2026-09-04T14:30:00Z',
  }
];

export const INITIAL_PICKUPS: Pickup[] = [
  {
    id: 'pkp-701',
    listingId: 'lst-ewaste-102',
    listingTitle: 'Batch of 18 Dual-Core Laptops & LED Display Panels',
    wasteType: 'E_WASTE',
    producerId: 'usr-producer-1',
    producerName: 'Apex Infotech Solutions',
    collectorId: 'usr-recycler-1',
    collectorName: 'GreenCycle E-Waste Recyclers',
    scheduledDate: '2026-09-06',
    timeSlot: '10:00 AM - 12:30 PM',
    pickupAddress: 'Plot 42, Tech Park, Gachibowli, Hyderabad',
    contactPerson: 'Karan Sharma (Facilities Head)',
    contactPhone: '+91 98765 43210',
    notes: 'Loading bay B4. Security clearance entry code: SW-8841.',
    status: 'SCHEDULED',
    createdAt: '2026-09-04T15:00:00Z',
  },
  {
    id: 'pkp-702',
    listingId: 'lst-organic-203',
    listingTitle: '180 kg Spent Espresso Coffee Grounds & Citrus Peel',
    wasteType: 'ORGANIC_WASTE',
    producerId: 'usr-producer-2',
    producerName: 'Grand Horizon Hotel & Banquet',
    collectorId: 'usr-farmer-1',
    collectorName: 'Rameshwar Organic Farming Co-op',
    scheduledDate: '2026-09-05',
    timeSlot: '04:00 PM - 06:00 PM',
    pickupAddress: '88 Circular Road, Jubilee Hills, Hyderabad',
    contactPerson: 'Chef Suresh Kumar',
    contactPhone: '+91 98123 77890',
    notes: 'Kitchen exit ramp near cold storage.',
    status: 'CONFIRMED',
    createdAt: '2026-09-04T16:00:00Z',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'ntf-01',
    userId: 'usr-producer-1',
    title: 'New High Bid Received!',
    message: 'GreenCycle E-Waste Recyclers placed a bid of ₹19,500 on your Server Motherboards listing.',
    type: 'BID',
    read: false,
    link: '/listings/lst-ewaste-101',
    createdAt: '2026-09-04T16:20:00Z',
  },
  {
    id: 'ntf-02',
    userId: 'usr-producer-2',
    title: 'Organic Waste Claimed',
    message: 'Rameshwar Organic Farming Co-op requested to claim your 450kg Vegetable Peelings.',
    type: 'CLAIM',
    read: false,
    link: '/listings/lst-organic-201',
    createdAt: '2026-09-05T08:15:00Z',
  },
  {
    id: 'ntf-03',
    userId: 'usr-recycler-1',
    title: '92% Smart Match Alert!',
    message: 'A new 65kg E-Waste listing near Gachibowli matches your recovery profile.',
    type: 'MATCH',
    read: true,
    link: '/matches',
    createdAt: '2026-09-04T10:35:00Z',
  }
];

export const INITIAL_MESSAGES: MessageItem[] = [
  {
    id: 'msg-101',
    senderId: 'usr-recycler-1',
    senderName: 'GreenCycle E-Waste Recyclers',
    receiverId: 'usr-producer-1',
    receiverName: 'Apex Infotech Solutions',
    listingId: 'lst-ewaste-101',
    listingTitle: '35 Dismantled Server Motherboards',
    content: 'Hello, can you confirm if the server boards contain lithium CMOS batteries or if they have been removed?',
    createdAt: '2026-09-04T16:25:00Z',
  },
  {
    id: 'msg-102',
    senderId: 'usr-producer-1',
    senderName: 'Apex Infotech Solutions',
    receiverId: 'usr-recycler-1',
    receiverName: 'GreenCycle E-Waste Recyclers',
    listingId: 'lst-ewaste-101',
    listingTitle: '35 Dismantled Server Motherboards',
    content: 'Hi GreenCycle! Yes, all CMOS batteries have been safely isolated and stored separately in compliance with safety norms.',
    createdAt: '2026-09-04T16:40:00Z',
  }
];
